---
- name: run erlang docker container
  hosts: all
  gather_facts: no

  vars:
    data_src_dir: /home/anton/progs/erlag
    data_dst_dir: /erlang

  tasks:
    - name: start erlang container
      docker:
        image=abaranov/erlang
        name=erlang
        detach=no
        state=running
        volumes={{data_src_dir}}:{{data_dst_dir}}

